services:
  backend:
    build:
      context: ./backend
    image: in-memory-db-service:latest
    restart: always
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/utils/health-check/"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  default:
    driver: bridge
