version: '3.8'

services:
  backend:
    build:
      context: ../backend
      dockerfile: ${DOCKERFILE:-Dockerfile}  # Use Dockerfile.dev for development
    image: in-memory-db-service:${TAG:-latest}
    restart: always
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=${ENVIRONMENT:-production}
      - DEBUG=${DEBUG:-false}
      - WORKERS=${WORKERS:-4}
      - CORS_ORIGINS=${CORS_ORIGINS:-http://localhost:8000}
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  default:
    driver: bridge
